### ISSUE TITLE
Provide integration with Run/Debug Configuration in IntelliJ

### ISSUE THREAD

**Issue by frgomes** [EECOLOR/little-spec#3]
It would be very handy if we could run/debug test cases under IntelliJ.

https://github.com/JetBrains/intellij-scala/tree/master/Runners/src/org/jetbrains/plugins/scala/testingSupport

**Comment by EECOLOR** [comment]
I am currently busy working on another project. On top of that, I am not using IntelliJ as my editor. There is a chance this issue will remain open quite some time.

You could provide it yourself. Executing tests is quite easy if I recall correctly. I am happy to answer any questions you have.

I will leave this issue open, both for questions and (possibly) a rainy Sunday where I find myself installing IntelliJ.

**Comment by frgomes** [comment]
I'm closing this issue.
Reason: little-spec implements TestFramework API from SBT. And IntelliJ supports this API.
So, there's not need for a special plugin for IntelliJ or any other IDE which supports SBT well.
Thanks ;-)

**Comment by EECOLOR** [comment]
Great to hear and thank you for making the effort to write that comment
